server:
  port: 8092

spring:
  application:
    name: ian-ddd-gateway
  profiles:
    active: dev

dubbo:
  application:
    name: ian-ddd-gateway
    qos-enable: false
    metadata-type: local
    metadata-service-protocol: injvm
  consumer:
    check: false

  metrics:
    export-metrics-service: false

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health
