server:
  port: 8092

spring:
  application:
    name: ${rootArtifactId}
  profiles:
    active: dev

dubbo:
  application:
    name: ${rootArtifactId}
    qos-enable: false
    metadata-type: local
    metadata-service-protocol: injvm
  consumer:
    check: false

  metrics:
    export-metrics-service: false

management:
  endpoints:
    web:
      exposure:
        include: health

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  is-read-header: true
  is-read-cookie: false
  is-read-body: false
  is-read-param: false
