server:
  port: 8092

spring:
  application:
    name: ${rootArtifactId}
  profiles:
    active: dev

dubbo:
  application:
    name: ${rootArtifactId}
    qos-enable: false
    metadata-type: local
    metadata-service-protocol: injvm
  consumer:
    check: false

  metrics:
    export-metrics-service: false

management:
  endpoints:
    web:
      exposure:
        include: health

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 900
  is-share: false
  is-read-header: true
  is-read-cookie: false
  is-read-body: false
  is-read-param: false

gateway:
  security:
    token:
      access-ttl: 15m
      refresh-ttl: 30d
      refresh-lock-wait: 3s
      refresh-lock-lease: 10s
